#ifndef _CHNSYSTHREAD_H_
#define _CHNSYSTHREAD_H_

#include "ChnsysTypes.h"

typedef VOID *OS_MUTEX_HANDLE;
OS_MUTEX_HANDLE OS_MUTEX_CreateInstance();
VOID OS_MUTEX_DestroyInstance(OS_MUTEX_HANDLE hOSMutex);
VOID OS_MUTEX_Lock(OS_MUTEX_HANDLE hOSMutex);
VOID OS_MUTEX_Unlock(OS_MUTEX_HANDLE hOSMutex);

typedef VOID *OS_CONDITION_HANDLE;
OS_CONDITION_HANDLE OS_CONDITION_CreateInstance();
VOID OS_CONDITION_DestroyInstance(OS_CONDITION_HANDLE hOSCondition);
VOID OS_CONDITION_Wait(OS_CONDITION_HANDLE hOSCondition, OS_MUTEX_HANDLE hOSMutex, CHNSYS_INT nTimeoutMilliSeconds);
VOID OS_CONDITION_Signal(OS_CONDITION_HANDLE hOSCondition);

typedef VOID *OS_THREAD_HANDLE;
OS_THREAD_HANDLE OS_THREAD_CreateInstance();
VOID OS_THREAD_DestroyInstance(OS_THREAD_HANDLE hOSThread);
typedef CHNSYS_BOOL (*OS_THREAD_CallBackFunc)(OS_THREAD_HANDLE hOSThread, int nThreadPhase, VOID *pContext);
VOID OS_THREAD_SetCallBack(OS_THREAD_HANDLE hOSThread, OS_THREAD_CallBackFunc cbf, VOID *pContext);
CHNSYS_BOOL OS_THREAD_Start(OS_THREAD_HANDLE hOSThread);
CHNSYS_BOOL OS_THREAD_Stop(OS_THREAD_HANDLE hOSThread, CHNSYS_BOOL bWait = TRUE);

#endif //_CHNSYSTHREAD_H_
